### ISSUE TITLE
[BUG]: WOW_PROJECT_ID is now WOW_PROJECT_WRATH_CLASSIC for Wrath

### ISSUE THREAD

**Issue by ascott18** [wardz/DRList-1.0#10]
### What happened?

Blizzard just released a patch that changed WOW_PROJECT_ID for Wrath Classic from WOW_PROJECT_BURNING_CRUSADE_CLASSIC to WOW_PROJECT_WRATH_CLASSIC.

### Is there any errors?

```shell
1x DRList-1.0-25\Spells-Spells.lua:477: DRList-1.0: Unsupported game expansion loaded.
<string>:"=[C]"]: in function "error"
[string "@11DRList-1.0-25\Spells-Spells.lua":477: in main chunk

Locals:
Lib = <table> {
 IsPVE = <func> @..\DRList-1.0.lua:315
 GetCategoryName = <func> @..\DRList-1.0.lua:305
 GetSpellCategory = <func> @..\DRList-1.0.lua:291
 IterateSpellsByCategory = <func> @..\DRList-1.0.lua:354
 GetNextDR = <func> @..\DRList-1.0.lua:324
 gameExpansion = "unknown"
 categoriesPvE = <table> {}
 L = <table> {}
 GetCategories = <func> @..\DRList-1.0.lua:265
 GetCategoryLocalization = <func> @..\DRList-1.0.lua:305
 GetSpells = <func> @..\DRList-1.0.lua:258
 diminishedDurations = <table> {}
 GetResetTime = <func> @..\DRList-1.0.lua:280
 GetCategoryBySpellID = <func> @..\DRList-1.0.lua:291
 IterateSpells = <func> @..\DRList-1.0.lua:354
 NextDR = <func> @..\DRList-1.0.lua:324
 resetTimes = <table> {}
 IsPvECategory = <func> @..\DRList-1.0.lua:315
 categoryNames = <table> {}
 GetPvECategories = <func> @..\DRList-1.0.lua:273
}
version = 25
```

### Game Version

Wrath of the Lich King

### Game Language

English

### Any additional info?

https://github.com/Gethe/wow-ui-source/commit/3eaa29bfc00a05362e4cf30921a5c0792fc47519#diff-239a2f4f8604d0b3956f4ee003b618690f95fbfb2c116e0d5fdc4e5cff41cb27R1105-R1106

**Comment by wardz** [comment]
Is this version 25? Latest is 42 which should work, although it still utilizes toc version query instead of `WOW_PROJECT_WRATH_CLASSIC`

**Comment by ascott18** [comment]
Ahh yeah, sorry, I had a really old local copy cloned from source. I only very quickly checked `master` here on GH to see that the constants were still being used, but I missed the workaround you had for wrath.

**Comment by wardz** [comment]
No worries, added now for consistency.
