### ISSUE TITLE
[BUG]: A little more info with the libs

### ISSUE THREAD

**Issue by sidamakid** [wardz/DRList-1.0#11]
### What happened?

Nothing is broken. Just wondering if you could make the template show more than it does right now. Like when the timer is up it prints out Spell has come off dr's or something?

### Game Version

Retail, The Burning Crusade Classic, Wrath of the Lich King, Classic Era

### Game Language

English

**Comment by wardz** [comment]
Diminish (which handles the timer part) is now retired sorry. It won't be getting any more updates except interface/toc version bumps until it breaks down completely. If you mean for DRList-1.0, it wont include timer events as that's a logistical nightmare and extremely time consuming to add with Blizzard's current API.
