### ISSUE TITLE
Add cataclysm classic spell support

### ISSUE THREAD

**Issue by glajchs** [wardz/DRList-1.0#17]
The list of spells with diminishing returns needs to be updated for cata.
Sorry I can't give more info, but the work needs to be done (and I expect it will be some fair amount of work)

**Comment by vendethiel** [comment]
Like #14 that was made a month ago?

**Comment by wardz** [comment]
v1.4.1 and greater supports cataclysm. The spell list is not 100% verified yet, but very close and will be added to over time.

**Comment by glajchs** [comment]
Ah, sorry I didn't see that! Yes I was coming from Curseforge and therefore missed the newer versions. Thank you for the hard work!
I thought I had checked for previous bugs but I didn't check well enough. :-)
