### ISSUE TITLE
Error loading everytime on client start 10.2.6

### ISSUE THREAD

**Issue by WuhbGaming** [wardz/DRList-1.0#18]
Happens every time with the 1.4.3, isn't present in previous version

**Comment by wardz** [comment]
What error you getting? Can't seem to reproduce it on my end

**Comment by WuhbGaming** [comment]
Message: Interface/AddOns/DRList-1.0/libs/LibStub/LibStub.lua:1 
Error loading Interface/AddOns/DRList-1.0/libs/LibStub/LibStub.lua
Time: Mon May  6 14:00:39 2024

**Comment by wardz** [comment]
Ah I never tested standalone install, only embedded. Will have it fixed in next release later today or tomorrow. Thanks for reporting.

**Comment by wardz** [comment]
Should be fixed now with v1.4.4.
