### ISSUE TITLE
Curseforge Packager embed usage is unconventional

### ISSUE THREAD

**Issue by ascott18** [wardz/DRList-1.0#2]
Typically, the main embeds xml file is contained in the root of the repo, so that when an external is declared in the .pkgmeta, the usage in the .toc file ends up like `Lib\DRList-1.0\DRList-1.0.xml`

However, DRList nests its main folder one level down, causing that conventional format to not work, instead requiring `Lib\DRList-1.0\DRList-1.0\DRList-1.0.xml`.

Since restructuring the folders at this point would break anything that is already using this, my suggestion would be to instead just to add a second `DRList-1.0.xml` at the root of the repo that then references the nested one.

**Comment by wardz** [comment]
Ah, didn't notice that. Thanks I will look into it.

**Comment by wardz** [comment]
Fixed it now.
