### ISSUE TITLE
Cata - Unstable Affliction Silence has no DR

### ISSUE THREAD

**Issue by XiconQoo** [wardz/DRList-1.0#20]
On Cata Beta Unstable Affliction Silence does not DR with anything, not even itself. Found nothing about this in the patchnotes though.

**Comment by XiconQoo** [comment]
A friend found this: https://www.youtube.com/watch?v=i1-ZQ81oFsY

Seems to be intended

**Comment by wardz** [comment]
Ty, fixed now. Makes sense I guess since Sin and Punishment dispell works the same.
