### ISSUE TITLE
Unmaintained for TBC?  Confirming claim

### ISSUE THREAD

**Issue by AlexFolland** [wardz/DRList-1.0#4]
In [this GladdyTBC comment](https://github.com/XiconQoo/Gladdy-TBC/pull/11#issuecomment-927945049), the author of Gladdy-TBC claimed that DRList has incorrect categories, and therefore they will maintain their own fork of DRData for TBC Classic.  This is a concerning direction, because now 2 different DRData forks are seemingly being maintained, which will cause fragmentation and duplicated development toward the same goal.

Is their claim true, or is DRList known to currently have completely correct DR categories for TBC Classic?

**Comment by wardz** [comment]
The addon is still maintained for Classic, TBC, Retail and eventually WotLK. If you find a missing spell or incorrect category feel free to submit an issue ticket or a pull request and I'll fix it asap.

Some **special** DR categories where the ability is supposed to only DR with itself such as `unstable_affliction`, `death_coil`, `freezing_trap`, `mind_control` are still included but unconfirmed in the lib. I haven't been able to test these in TBC sadly, and there's no user reports available. The rest of the DR categories works fine in TBC.

**Comment by AlexFolland** [comment]
Thanks for the response.  I've continued the discussion in the thread with the original claim.  This can be closed.
