### ISSUE TITLE
[BUG]: Wrong DRs TBC

### ISSUE THREAD

**Issue by XiconQoo** [wardz/DRList-1.0#5]
### What happened?

Yo @wardz, I am the author of Gladdy.

I recently tested DRs extensively on PTR. My self-maintained DR-lib is quite accurate now. You might want to take a look and find diffs

-> https://github.com/XiconQoo/Gladdy-TBC/blob/main/Libs/DRData-1.0/DRData-1.0.lua

### Game Version

The Burning Crusade Classic

### Game Language

English, French, German, Italian, Korean, Chinese, Russian, Spanish, Brazil

**Comment by wardz** [comment]
Hey, thanks a lot, will look into it asap! I prob won't be playing WoW again untill Wotlk gets released so this is extremely helpful :partying_face:

**Comment by wardz** [comment]
Just to confirm, does disarms and Improved Wing Clip not have DRs in TBC?

**Comment by XiconQoo** [comment]
Actually I did not test disarm. Since warrior (to my knowledge) is the only class in TBC to be able to disarm, I neglected it.

**Comment by vendethiel** [comment]
As a user of drtracker (for gladiusex), this being updated would be nice :)

**Comment by wardz** [comment]
Added now in v1.2.8. Thanks again.

> Since warrior (to my knowledge) is the only class in TBC to be able to disarm, I neglected it. For completeness you can add it, as it definetely has a DR.

Rogues got disarm aswell with Riposte talent. But yeah in arena you wont really see this DR 99% of the time, it's more for BGs/world pvp.
